version: '3.8'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
  app:
    depends_on:
      - mysqldb
    image: red-panda-bank
    build: .
    env_file: ./.env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url" = "jdbc:mysql://localhost:$DB_DOCKER_PORT/$MYSQL_DATABASE?serverTimezone=UTC"
      "spring.datasource.driver-class-name" = "com.mysql.jdbc.Driver"
      "spring.datasource.username" = "$MYSQL_USER"
      "spring.datasource.password" = "$MYSQL_PASSWORD" 
      "spring.jpa.properties.hibernate.dialect" = "org.hibernate.dialect.MySQL8Dialect"
      "spring.jpa.generate-ddl" = "true"
      "spring.jpa.hibernate.ddl-auto" = "update"
      "spring.jpa.show-sql" = "true"
      }'
